let data = [
    {
        id: 1,
        name: "Amazing Digital Art 1",
        image_url: "/assets/Card/product-img1.png",
        seller_img: "/assets/Card/seller1.png",
        seller_name: "@ashil",
        likes: 3,
        stock: 5,
        price: 1.8,
    },
    {
        id: 2,
        name: "Amazing Digital Art 2 ",
        image_url: "/assets/Card/product-img2.png",
        seller_img: "/assets/Card/seller1.png",
        seller_name: "@ashil",
        likes: 0,
        stock: 5,
        price: 3.5,
    },
    {
        id: 3,
        name: "Amazing Digital Art 3",
        image_url: "/assets/Card/product-img3.png",
        seller_img: "/assets/Card/seller1.png",
        seller_name: "@ashil",
        likes: 2,
        stock: 5,
        price: 2.3,
    },
    {
        id: 4,
        name: "Amazing Digital Art 4",
        image_url: "/assets/Card/product-img4.png",
        seller_img: "/assets/Card/seller1.png",
        seller_name: "@ashil",
        likes: 10,
        stock: 5,
        price: 6.5,
    },
    {
        id: 5,
        name: "Amazing Digital Art 5",
        image_url: "/assets/Card/product-img1.png",
        seller_img: "/assets/Card/seller1.png",
        seller_name: "@ashil",
        likes: 3,
        stock: 5,
        price: 1.8,
    },
    {
        id: 6,
        name: "Amazing Digital Art 6 ",
        image_url: "/assets/Card/product-img2.png",
        seller_img: "/assets/Card/seller1.png",
        seller_name: "@ashil",
        likes: 0,
        stock: 5,
        price: 3.5,
    },
    {
        id: 7,
        name: "Amazing Digital Art 7",
        image_url: "/assets/Card/product-img3.png",
        seller_img: "/assets/Card/seller1.png",
        seller_name: "@ashil",
        likes: 2,
        stock: 5,
        price: 2.3,
    },
    {
        id: 8,
        name: "Amazing Digital Art 8",
        image_url: "/assets/Card/product-img4.png",
        seller_img: "/assets/Card/seller1.png",
        seller_name: "@ashil",
        likes: 10,
        stock: 5,
        price: 6.5,
    },
    {
        id: 9,
        name: "Amazing Digital Art 1",
        image_url: "/assets/Card/product-img1.png",
        seller_img: "/assets/Card/seller1.png",
        seller_name: "@ashil",
        likes: 3,
        stock: 5,
        price: 1.8,
    },
    {
        id: 10,
        name: "Amazing Digital Art 2 ",
        image_url: "/assets/Card/product-img2.png",
        seller_img: "/assets/Card/seller1.png",
        seller_name: "@ashil",
        likes: 0,
        stock: 5,
        price: 3.5,
    },
    {
        id: 11,
        name: "Amazing Digital Art 3",
        image_url: "/assets/Card/product-img3.png",
        seller_img: "/assets/Card/seller1.png",
        seller_name: "@ashil",
        likes: 2,
        stock: 5,
        price: 2.3,
    },
    {
        id: 12,
        name: "Amazing Digital Art 4",
        image_url: "/assets/Card/product-img4.png",
        seller_img: "/assets/Card/seller1.png",
        seller_name: "@ashil",
        likes: 10,
        stock: 5,
        price: 6.5,
    },
    {
        id: 13,
        name: "Amazing Digital Art 5",
        image_url: "/assets/Card/product-img1.png",
        seller_img: "/assets/Card/seller1.png",
        seller_name: "@ashil",
        likes: 3,
        stock: 5,
        price: 1.8,
    },
    {
        id: 14,
        name: "Amazing Digital Art 6 ",
        image_url: "/assets/Card/product-img2.png",
        seller_img: "/assets/Card/seller1.png",
        seller_name: "@ashil",
        likes: 0,
        stock: 5,
        price: 3.5,
    },
    {
        id: 15,
        name: "Amazing Digital Art 7",
        image_url: "/assets/Card/product-img3.png",
        seller_img: "/assets/Card/seller1.png",
        seller_name: "@ashil",
        likes: 2,
        stock: 5,
        price: 2.3,
    },
    // {
    //     id: 16,
    //     name: "Amazing Digital Art 8",
    //     image_url: "/assets/Card/product-img4.png",
    //     seller_img: "/assets/Card/seller1.png",
    //     seller_name: "@ashil",
    //     likes: 10,
    //     stock: 5,
    //     price: 6.5,
    // },
]

export default data;