import React from 'react'
import Head from 'next/head'
import Navbar from '../../components/Navbar/Navbar'

import Discover from '../../components/Discover/Discover'
import { ToastContainer, toast } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import Footer from '../../components/Footer'
import { useRouter } from 'next/router'

const discover = () => {
  const router = useRouter()
  const categoryName = router?.query?.category
  console.log('categoryName', categoryName)
  return (
    <>
      <Head>
        <title>Epiko NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.svg" />
      </Head>
      <Navbar />
      <Discover categoryName={categoryName} />
      <ToastContainer
        position="top-center"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
      />
      <Footer />
    </>
  )
}

export default discover
