const actionTypes = {
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  SET_WEB3: 'SET_WEB3',
  SET_NFT_ONSALE: 'SET_NFT_ONSALE',
  SET_NFT_CREATED_BY_USER: 'SET_NFT_CREATED_BY_USER',
  SET_PROFILE: 'SET_PROFILE',
  SET_ACTIVITY: 'SET_ACTIVITY',
}

export default actionTypes
