import React from 'react'
import Head from 'next/head'
import Navbar from '../components/Navbar/Navbar'
import Footer from '../components/Footer'
import Create from '../components/CreateNFT/Create'
import { ToastContainer, toast } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import withAuth from '../components/HOC/withAuth'

// import Create from '../components/CreateNFT/Create'
// import toast, { Toaster } from 'react-hot-toast'
// import Footer from '../components/Footer'

const create = () => {
  return (
    <>
      <Head>
        <title>Epiko NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.svg" />
      </Head>
      <Navbar />
      <Create />
      <ToastContainer
        position="top-center"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        />
      <Footer />
    </>
  )
}

export default withAuth(create)
