import React, { useEffect } from 'react'
import Head from 'next/head'
import Navbar from '../components/Navbar/Navbar'

import Faqs from '../components/Faqs'
import { ToastContainer, toast } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import Discover from '../components/Discover/Discover'
import { useStateValue } from '../context/context'
import axios from 'axios'
import actionTypes from '../context/action-types'
import ItemSlider from '../components/ItemSlider'
import url from '../data'
import Footer from '../components/Footer'

const single = () => {
  const [{ createdNft }, dispatch] = useStateValue()

  useEffect(() => {
    axios
      .post(`${url}/nft/nftListing`, {
        length: 20,
        start: 0,
        sTextsearch: '',
        sCategory: '',
        sSortingType: '',
        sSellingType: '',
      })
      .then((response) => {
        dispatch({
          type: actionTypes.SET_NFT_CREATED_BY_USER,
          payload: response?.data?.data?.data,
        })
      })
  }, [])
  return (
    <>
      <Head>
        <title>Epiko NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.svg" />
      </Head>
      <Navbar />
      <Faqs />
      <ItemSlider createdNft={createdNft} />
      <ToastContainer
        position="top-center"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
      />
      <Footer />
    </>
  )
}

export default single
