import type { NextPage } from 'next'
import Head from 'next/head'

import Hero from '../components/Hero/Hero'
import Navbar from '../components/Navbar/Navbar'
import ItemSlider from '../components/ItemSlider'
import Topusers from '../components/Topusers'
import Connect from '../components/Connect'
import { useEffect } from 'react'
import axios from 'axios'
import actionTypes from '../context/action-types'
import { useStateValue } from '../context/context'
import { ToastContainer, toast } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { useWeb3React } from '@web3-react/core'
import url from '../data'
import Footer from '../components/Footer'
import EpikoRegal from '../components/EpikoRegal'

const Home: NextPage = () => {
  const [{ onSaleNft, createdNft }, dispatch] = useStateValue()
  const token = localStorage.getItem('auth_pass')
  const { library: web3 } = useWeb3React()

  useEffect(() => {
    try {
      axios
        .post(`${url}/nft/nftListing`, {
          length: 10,
          start: 0,
          sTextsearch: '',
          sCategory: 'All',
          sSortingType: 'Recently Added',
          sSellingType: '',
        })
        .then((response) => {
          console.log(response)

          dispatch({
            type: actionTypes.SET_NFT_CREATED_BY_USER,
            payload: response?.data?.data?.data,
          })
        })
    } catch (e) {
      console.log(e)
    }
  }, [])

  useEffect(() => {
    web3?.eth.net.getId().then((netId: any) => {
      switch (netId) {
        case 1:
          toast.warn('This is mainnet. Please login to Rinkeby to continue.')
          break
        case 4:
          // toast('This is Rinkeby Network.')
          break
        default:
          toast.warn('This is network is not supported. Please login to Rinkeby to continue.')
      }
    })
  }, [web3])

  useEffect(() => {
    try {
      if (!window.ethereum) {
        // window.alert("You must install MetaMask to use this website");
        toast.error("You must install MetaMask to use this website",{
          position: "top-center",
          autoClose: false,
          hideProgressBar: false,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
          })
        return;
      }
    } catch (e) {
      toast.error("Error");
    }
  }, [])

  return (
    <>
      <Head>
        <title>Epiko NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.svg" />
      </Head>
      <Navbar />
      <Hero />
      <ItemSlider createdNft={createdNft} />
      <Topusers />
      {/* <Connect /> */}
      <EpikoRegal />
      <ToastContainer
        position="top-center"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
      />
      <Footer />
    </>
  )
}

export default Home
